### PR TITLE
@generic annotation to suppress miniboxing warnings #194

### PR DESCRIPTION
**Pull request by milosstojanovic**
Added possibility to suppress miniboxing warnings by adding @generic annotation.

 I added one additional boolean parameter to suboptimalCodeWarning method which says if annotation is present. Another possibility is to check if annotation is present before calling the method suboptimalCodeWarning, but in that case if new code is added that check can be easily forgotten and by passing the parameter you will be forced to take care of it. Anyways, I left it as an optional parameter with default value false. What do you think about that? 

I tested it with some warnings but not all of them. Is there some documentation maybe about all the possible miniboxing warnings with the test cases which will cause them? I was not able to understand and make test cases for all of them.

### CODE REVIEW

**Comment by VladUreche** [comment]
Nice, thanks @milosstojanovic!

Could you please rebase so we don't lose the latest changes? I'm sure there are more elegant ways, but here's the very verbose way I would do this:

```
git remote add trunk https://github.com/miniboxing/miniboxing-plugin.git
git fetch trunk 
git checkout origin/master -b temp
git branch -D temp
git branch -D wip
git checkout trunk/wip -b wip
git cherry-pick cff3a4c
git commit --amend # Update message, if needed
git cherry-pick  5c15ee9
git commit --amend # Update message, if needed
git push origin wip -f
```

**Comment by VladUreche** [comment]
By latest changes, I mean https://github.com/miniboxing/miniboxing-plugin/commit/8df06b4d32f2faea7add9d0703a6a6318dc5ffc7, which got reverted in this PR :(

**Comment by VladUreche** [comment]
By the way, you can reference the bug in the commit messages (#194)

**Comment by milosstojanovic** [comment]
Replaced by https://github.com/miniboxing/miniboxing-plugin/pull/198

**Pull request closed without merging**
