### PR TITLE
Issue #155 - MiniboxedTuple automatic rewiring

### PR DESCRIPTION
**Pull request by milosstojanovic**
Automatic rewiring for MbTuples constructors and accessors

### CODE REVIEW

**Comment by milosstojanovic** [comment]
Review by @VladUreche

**Comment by VladUreche** [comment]
Thanks @milosstojanovic! Aside from the warning messages, it seems there's a snag in the 2.10 test suite -- see https://travis-ci.org/miniboxing/miniboxing-plugin/builds/58965256 for details. The usual fix is to introduce a replacement rule in [`TestSuite.scala`](https://github.com/miniboxing/miniboxing-plugin/blob/wip/tests/correctness/test/miniboxing/infrastructure/TestSuite.scala#L15-L47).

**Comment by VladUreche** [comment]
Btw, to reproduce the error on your machine, do this:

```
$ cd miniboxing-plugin
$ sbt
...
> ++ 2.10.4
> test
```

**Comment by VladUreche** [comment]
LGTM, thank you @milosstojanovic!

**Pull request merged**
