### PR TITLE
Issue #194 - Add @generic annotation so minibox warnings can be suppressed

### PR DESCRIPTION
**Pull request by milosstojanovic**
Added possibility to suppress miniboxing warnings by adding @generic annotation.

I added one additional boolean parameter to suboptimalCodeWarning method which says if annotation is present. Another possibility is to check if annotation is present before calling the method suboptimalCodeWarning, but in that case if new code is added that check can be easily forgotten and by passing the parameter you will be forced to take care of it. Anyways, I left it as an optional parameter with default value false.

### CODE REVIEW

**Comment by VladUreche** [comment]
Nice work @milosstojanovic! Can you also upload your test cases?

**Comment by VladUreche** [comment]
@milosstojanovic, any update on this?

**Comment by milosstojanovic** [comment]
I added test cases with suppressed minibox warnings using @generic annotation and without it as we discussed.

**Comment by VladUreche** [comment]
LGTM! Thanks a lot @milosstojanovic, very nice work!

**Pull request merged**
