### PR TITLE
Closes#63

### PR DESCRIPTION
**Pull request by VladHaprian**
I tried to fix the bug

### CODE REVIEW

**Comment by VladUreche** [comment]
Vlad, thanks a lot for the initial pull request! Here are some things that need to be addressed:
- [ ] please add `.metadata` to the `.gitignore` file and unstage all files from `.metadata`: https://github.com/miniboxing/miniboxing-plugin/pull/80/files
- [ ] your changes reformatted `components/plugin/src/miniboxing/plugin/transform/spec/MiniboxSpecTreeTransformer.scala` accoding to Java rules, which makes it almost unreadable -- please revert that change
- [ ] for the test, please rename it to `gh-bug-63.{scala, check, flags}`
- [ ] please check the [tests that are failing](https://travis-ci.org/miniboxing/miniboxing-plugin/builds/21193101) -- some of them may need to be updated
- [ ] the commit should be named "Closes #63"
- [ ] regarding the crash at the end of the [Travis build](https://travis-ci.org/miniboxing/miniboxing-plugin/builds/21193101), once you fix the points above, ping me and I will have a look

**Comment by VladHaprian** [comment]
I tried to fix the tests. All are ok except 2 of them , namely mb_speck_hijack1.scala and mb_speck_hijack2.scala where I get the next error :scala.reflect.internal.MissingRequirementError: class scala.miniboxed in compiler mirror not found.

**Comment by VladUreche** [comment]
Hmm, not okay. If you look at the new `.check` files, you will see that all of them have the same error, that `scala.miniboxed` was not found: https://github.com/HaprianVlad/miniboxing-plugin/commit/3c6aa9ee0d61745932773e7a77c1c4eadbc0b623#diff-52

That's certainly not going to work. Additionally, when you push new commits please squash them: http://stackoverflow.com/questions/5189560/how-can-i-squash-my-last-x-commits-together-using-git

**Comment by VladUreche** [comment]
This PR was superseded by the following two commits: 7bb9da34474183e4d3c0017dab47c2d809559990 and 3d9313c07dc2cd4b8b3a5259e427fc909fe4fe87

**Pull request closed without merging**
